Sb dev ip check
ucd-library/ucdlib-theme pull request #52
Opened 2022-03-30 18:07 UTC by sbagg

This is IP check util class

2022-03-30 19:49 UTC, spelkey-ucd requested changes
wow, fast! a few changes:

1. Since it's not actually a lit controller, let's move it up out of the controllers section and into the root of utils
2. Instead of testing if the ip is in a range using regex, use CIDR with [this package](https://www.npmjs.com/package/ip-cidr). Also, our good buddy Justin actually already [coded some of this up for you](https://github.com/ucd-library/vessel/blob/main/node-utils/lib/auth.js#L130).
3. Lets ALSO check if the ip is on the vpn.
4. instead of bailing if you find an ipv6, go get their [ipv4](https://api.ipify.org?format=json) and run the range tests on that. i don't think anyone only has an ipv6...
5. document both the class and the methods using [jsdoc syntax](https://jsdoc.app/) with at least `description`, `param` and `returns`.

2022-03-31 21:04 UTC, spelkey-ucd commented on elements/utils/ip-check.js
> +    this.isIP6 = false;
this will override line 57. also, store the ipv6 address in addition to the ipv4

2022-03-31 21:14 UTC, spelkey-ucd commented on elements/utils/ip-check.js
> +  isInVPN(){
this should also be done through ip-cidr. I just jumped on the vpn and got assigned an ip of `128.120.238.136`, which does not equal any of the values in `this.ipVPNRange`

2022-04-05 15:45 UTC, spelkey-ucd commented
looking really good. worked great for me. three small tweaks before i merge and publish to npm:

1. Take `this.runIP();` out of the class constructor since constructors can't have `await` statements. Using the utility will be a two part process: 
```
    this.IpDetect = new IpDetect();
    await this.IpDetect.runIP();
   // then do work
  if ( this.ipDetect.isResult ) {}
  ```
This way, we know the fetch process has completed before doing stuff with the results

2. Ask James for the range for the library staff vpn, and include them in `this.ipVPNRange`, but put a comment or something so we know they are for the library staff vpn.
3. Change the name of `isResult ` to `isOnCampus` or something more descriptive.

2022-04-05 17:32 UTC, sbagg commented
Using it would be this process:

`  import {IpDetect} from "../../elements/utils/ip-check.js";

    async ip_check(){
      this.ip = new IpDetect();
      await this.ip.runIP();

    console.log("This IP:", this.ip.isOnCampus);
    return this.ip.isOnCampus

  }`
then run the ip_check() somewhere

2022-04-05 18:12 UTC, merged